#!/bin/bash
set -euo pipefail

SECURITY_DIR="$HOME/security"
KEYSTORE_FILENAME="lena-miyamoto-keystore.kdbx"
KEYSTORE_BACKUP_FILENAME="lena-miyamoto-keystore_$(date +%Y-%m-%d).kdbx"

cp -vf "$SECURITY_DIR/$KEYSTORE_FILENAME" "$SECURITY_DIR/$KEYSTORE_BACKUP_FILENAME"
proton-drive fs upload "$SECURITY_DIR/$KEYSTORE_BACKUP_FILENAME" '/my-files/security/'
rm -vf "$SECURITY_DIR/$KEYSTORE_BACKUP_FILENAME"
